/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.apache.maven.plugins.maven.surefire.plugin)
    api(libs.org.apache.maven.plugins.maven.jar.plugin)
    api(libs.com.code.intelligence.jazzer.junit)
    api(libs.org.seleniumhq.selenium.selenium.java)
    runtimeOnly(libs.com.mysql.mysql.connector.j) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.google.protobuf", "module" to "protobuf-java"))
    }
    runtimeOnly(libs.com.h2database.h2)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.net.jqwik.jqwik.api)
    testImplementation(libs.io.github.bonigarcia.webdrivermanager)
    compileOnly(libs.org.projectlombok.lombok)
}

group = "org.example"
version = "0.0.1-SNAPSHOT"
description = "Banco-CRUD"
java.sourceCompatibility = JavaVersion.VERSION_22
java.targetCompatibility = JavaVersion.VERSION_22

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
